### ISSUE TITLE
free text search

### ISSUE THREAD

**Issue by fils** [SemanticComputing/fuseki-docker#1]
Curious, when loading data into this system I can perform basic SPARQL just fine.  
However, when I try a free text search I get results that are obviously wrong.   Is there some need to perform a free text index build to get free text queries to work?

I try a search with "Anders" which I know is a literal value (substring) of this predicate.   However, I get returns that don't have this string present at all.

Any ideas?   

Other than this, I can load and query data just fine...

Thanks
Doug

```SPARQL
PREFIX text: <http://jena.apache.org/text#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?s ?proj ?pi
{  
   ?s  text:query  "Anders" .
   ?s  <http://opencoredata.org/id/voc/csdco/v1/project> ?proj .
   ?s  <http://opencoredata.org/id/voc/csdco/v1/pi> ?pi .
}
```

**Comment by fils** [comment]
@esikkala I see that file now and I just edited it and added in my predicates I want to index

```
@prefix csdco:  <http://opencoredata.org/id/voc/csdco/v1/> .
...
<#entity-map> a text:EntityMap ;
    text:entityField "uri" ;
    text:graphField "graph" ; ## enable graph-specific indexing
    text:defaultField "text" ; ## Must be defined in the text:map
    text:uidField "uid" ;
    text:map (
         [ text:field "text" ; text:predicate skos:prefLabel ]
         [ text:field "text" ; text:predicate skos:altLabel ]
         [ text:field "text" ; text:predicate skos:hiddenLabel ]
         [ text:field "text" ; text:predicate rdfs:label ]
         [ text:field "text" ; text:predicate csdco:location ]
         [ text:field "text" ; text:predicate csdco:pi]
         )
    .```

still no luck...  I was hoping this was it.  :)  
I'll keep trying some iterations...

**Comment by fils** [comment]
As a test I went in and added in

```
<http://opencoredata.org/id/resource/csdco/feature/mncl-1cw08-1a> <http://www.w3.org/2000/01/rdf-schema#label> "Ander Noren" .
```

to my RDF and tried

```SPARQL
PREFIX text: <http://jena.apache.org/text#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX csdco: <http://opencoredata.org/id/voc/csdco/v1/>
SELECT ?s  
{  
   ?s  text:query "Anders" .
}
```

again I got an empty set return.    I see now my previous errors were simply due to my predicates not being indexed.  However, I did expect to see this one triple return now that I included an rdfs:label for it (which all my resource should really have!  I'll fix that here here later..  bad form on my part).

**Comment by jiemakel** [comment]
Just to make sure, in the above you add the triple with a label of `"Ander Noren"`, (without an s) but query for `"Anders"`, which obviously wouldn't match. Is this the problem or is it just a typo when you copied the example here to GitHub?

**Comment by fils** [comment]
@jiemakel my apologies for leaving this thread hanging..   yes, it was a combination of typos on my part and also not understanding how to set up the indexing correctly.  I'm been using the text search ability just fine now.   Feel free to close and I'll try and watch my github issues closer.. ;)
