### ISSUE TITLE
Maintaining new fuseki versions

### ISSUE THREAD

**Issue by kdejaeger** [SemanticComputing/fuseki-docker#10]
Hello,

I was wondering if this project is still going to be updated to stay up to date with new fuseki versions?
@yoge1 ?

**Comment by kdejaeger** [comment]
I was able to reach @yoge1  and he move to a new macbook that still needs some finetuning. So this will be taken care of.

**Comment by yoge1** [comment]
Hi, just to let you know, I just updated the Dockerfile in this repo and the image in Docker Hub to use latest Fuseki version (4.5.0).

**Comment by kdejaeger** [comment]
Thanks a lot
