### ISSUE TITLE
Compact doesn't finish occasionally

### ISSUE THREAD

**Issue by kdejaeger** [SemanticComputing/fuseki-docker#15]
We compact every 12 hours to go from like 60GB's to a few MB's ... . I still find this mind boggling :).
It occured three times now on the 4.6.1 verion, that the compact doesn't generate a 'finish'/'success' key/value. Unfortunately a big pain in the ass on azure/kubernetes since it requireds a larger disc every time. We will add some disc monitoring to avoid this.

I'm going to upgrade to 4.7.0 and will report here again if it occurs again when the compact 'hangs'.
I don't believe there's release notes for this project? How can I figure out what's in 4.7.0. A github link, tags, compare revisions? I believe work was done on compact/backup.

**Comment by yoge1** [comment]
I'm not familiar with the compact functionality. Please do share your notes when testing on 4.7.0.
Regarding Jena release notes, have you checked:

GitHub closed issues for Jena 4.7.0: https://github.com/apache/jena/issues?q=is%3Aissue+closed%3A2022-09-01..2022-12-31

JIRA issues for Fuseki: https://issues.apache.org/jira/browse/JENA-2346?jql=project%20%3D%20JENA%20AND%20component%20%3D%20Fuseki

New Jena releases are announced on mailing list users@jena.apache.org:
https://jena.apache.org/help_and_support/#email-support-lists

**Comment by yoge1** [comment]
I'm closing the issue, as this seems to be an issue with Fuseki itself. Please re-open if necessary.
