### ISSUE TITLE
Newb question on docker state (im)permanence

### ISSUE THREAD

**Issue by rjalexa** [SemanticComputing/fuseki-docker#20]
Dear friends just a docker/fuseki newbie question.

I have this docker working very well with two bind mounts to host directory for the databases and configuration.

Yesterday via the Fuseki web interface I had deleted two datasets, the default DS and a MEMATEST and kept only one single MEMA dataset for my application. All good.

Today I needed to stop the docker and restart it and much to my surprise the two datasets I had deleted are back in the interface.

Can you please help me understand why is this happening?

Just to be sure if I add data from TTLs via the s-post program, and then need to stop and restart, will I lose data?

Thanks for clearing up my confusion.

**Comment by yoge1** [comment]
The default dataset "ds" configured in the `assembler.ttl` file cannot really be deleted via the Fuseki web interface. You can technically do that, but after docker container restart the "ds" dataset appears once again in the interface. Thus, I think you cannot delete any dataset that is configured in the `assembler.ttl` via the interface – you need to edit `assembler.ttl` for that (and delete database/index files manually on the filesystem).

Regarding the other dataset "MEMATEST" – how was this created? If via the Fuseki web interface, it should stay deleted once it has been deleted via the interface.

> Just to be sure if I add data from TTLs via the s-post program, and then need to stop and restart, will I lose data?

If the data is persisted on the host file system – as it should be as you are using a bind mount for the databases – you shouldn't lose data if you stop/restart the docker container (you can even do `docker rm` and create a new container to access the data loaded with the previous container).

**Comment by rjalexa** [comment]
Thank you very much. I appreciate your help!
