### ISSUE TITLE
Updating lucene index raises exception when the service is running

### ISSUE THREAD

**Issue by vtrgdu** [SemanticComputing/fuseki-docker#21]
Maybe this is not an issue, but just my fault. In any case, I'd appreciate any help.

I have an indexed dataset that needs to be updated daily, which I do by calling s-post on the fresh ttls in the running docker instance. However, in my (limited) understanding, I also have to refresh the lucene index. To do that, I subsequently call jena.textindexer, but at this point I get the following java exception:

org.apache.jena.assembler.exceptions.AssemblerException: caught: Failed to get a lock: file='/fuseki-base/<dataset_path>/tdb.lock'

As I expected for a lock issue, the operation succeedes if I stop the docker and run the indexer from the outside.

Now the question is: am I missing something? Or stopping the docker is the correct way to update lucene indexes?

Thank you in advance for any advice and forgive me if this is a trivial question

**Comment by yoge1** [comment]
Based on my understanding, if you load data into a live Fuseki, e.g. using s-post, the lucene text index gets updated automatically ("Once configured, any data added to the text dataset is automatically indexed as well"; see [documentation](https://jena.apache.org/documentation/query/text-query.html#configuration)).

You only need to manually run jena.textindexer if you want to load RDF data using a tdb/bulk loader (or if you have an existing TDB dataset for which you want to create a text index) (see [documentation](https://jena.apache.org/documentation/query/text-query.html#building-a-text-index)). And for that, you need to stop the Fuseki docker.
