### ISSUE TITLE
JDK 19 is EOL

### ISSUE THREAD

**Issue by berezovskyi** [SemanticComputing/fuseki-docker#24]
https://javaalmanac.io/jdk/ says JDK 19 is EOL for quite a while now. Is there a chance you could switch the container base to 17 or 21, please?

Additionally, https://hub.docker.com/_/openjdk seems to be EOLed too. Thus, I'd probably suggest to switch to `eclipse-temurin:21-jdk` as a new base. `azul/zulu-openjdk-debian:21-latest` and `azul/zulu-openjdk:21-latest` should be good choices too.

P.S. Thank you for putting together this container and keeping it updated.

**Comment by yoge1** [comment]
Thanks for pointing that out!

The container base image has now been switched to `eclipse-temurin:21-jre-alpine` (https://github.com/SemanticComputing/fuseki-docker/commit/7b21eb504ab7da1a40ccefe192f29a4281c9b515).
