### ISSUE TITLE
Can anyone hep with this great docker image performance?

### ISSUE THREAD

**Issue by rjalexa** [SemanticComputing/fuseki-docker#25]
Are there any parameters or other "tricks" to help with handling more connections? Thanks a lot very grateful for your work.

**Comment by yoge1** [comment]
For tuning Fuseki for performance, see e.g. [FusekiTuning](https://github.com/NatLibFi/Skosmos/wiki/FusekiTuning) on Skosmos project. E.g. you can provide your custom Jetty configuration file as a --jetty-config=FILE parameter by overriding the CMD command of the Dockerfile.

For questions on using Fuseki, feel free to contact the [jena users list](https://jena.apache.org/help_and_support/).
