### ISSUE TITLE
Resolving System Crashes When Inserting Large Volumes of Triples in Fuseki

### ISSUE THREAD

**Issue by Myasir92** [SemanticComputing/fuseki-docker#27]
I am using Fuseki to insert statements with SPARQL queries. In each request, I insert about 7-8 triples. I started with a loop of 1 million iterations, but the loop reached 320,000 iterations when approximately 2.2 million triples were inserted, which caused the system to crash. I am running Fuseki through Docker, where I have assigned 8GB of memory. After restarting Fuseki, it works fine again. Can you provide insights on how to resolve this issue and explain why it happened?

@kdejaeger  @ptleskin @razz0 @jiemakel

**Comment by yoge1** [comment]
I wonder if this is related to Fuseki itself, and not this Docker recipe (this repository) for it.

Are you able to run Fuseki without Docker ([Download Fuseki with UI](https://jena.apache.org/documentation/fuseki2/#download-fuseki-with-ui)
 and run [Fuseki as a Standalone Server](https://jena.apache.org/documentation/fuseki2/fuseki-webapp.html)) and see if the issue persists?

**Comment by yoge1** [comment]
Also, would it be possible for you to try assigning more memory to Docker?
