### ISSUE TITLE
ENABLE_UPDATE doesn't seem to work

### ISSUE THREAD

**Issue by AtomsForPeace** [SemanticComputing/fuseki-docker#3]
I run the following command:
`docker run --rm -it -p 3030:3030 --name fuseki -e ADMIN_PASSWORD=PASSWORD -e ENABLE_DATA_WRITE=true -e ENABLE_UPDATE=true -e ENABLE_UPLOAD=true secoresearch/fuseki`

I then do a simple update like:
```
INSERT DATA {
	<blah.com> <what> "test"
}
```

Then when I make a select all triples I get 0 results.

I don't see any errors in the terminal window where docker is running.

**Comment by esikkala** [comment]
If you don't specify a graph in your update query, the triples go to the default graph. You can select them like this: 
```
SELECT ?s ?p ?o
WHERE {
  GRAPH <urn:x-arq:DefaultGraph> {
    ?s ?p ?o
  }
}
```
More info: https://jena.apache.org/documentation/tdb/datasets.html

**Comment by AtomsForPeace** [comment]
Thanks very much for the quick reply.
It works when I do that indeed.

I just don't quite understand why when I use the web interface (after starting fuseki myself) it works without specifying the DefaultGraph. Surely the behavior should be the same on both, right?
