### ISSUE TITLE
Is there a way to change the port from 3030 to 443?

### ISSUE THREAD

**Issue by n16** [SemanticComputing/fuseki-docker#4]
I need to deploy this service on my server. My server only allows for incoming (ingress) requests to come in port 443. Can you let me know if I can change the port to 443? 
Changing the port using -p attribute didn't work.
Thank you.

**Comment by esikkala** [comment]
The -p flag should do the trick. See that you have used it correctly: https://docs.docker.com/config/containers/container-networking/

**Comment by n16** [comment]
Yes, @esikkala, that is when you run in using the command line. But what about if I want to embed it in the Dockerfile?
What I'm trying to do is to deploy it on a host that only allows 443 for ingresses, so I need to change the listening port to be 443. I tried it in the deployment.yml K8 file, but didn't work. Do you have any solutions for that?

**Comment by esikkala** [comment]
If you are using Kubernetes for running this container, then you need study how the port on your server (443) is mapped to the port that is exposed inside this container (8080). It seems that you can do that with "nodePort" and "targetPort" variables in Kubernetes YAML file: https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-ports-targetport-nodeport-service.html
