### ISSUE TITLE
log4j vulnerability

### ISSUE THREAD

**Issue by xgaia** [SemanticComputing/fuseki-docker#9]
Hello,

This image is concerned by the log4j vulerability

```bash
docker scan secoresearch/fuseki | grep log4j 
```

```
  Upgrade org.apache.logging.log4j:log4j-core@2.14.1 to org.apache.logging.log4j:log4j-core@2.15.0 to fix
  ✗ Arbitrary Code Execution (new) [Critical Severity][https://snyk.io/vuln/SNYK-JAVA-ORGAPACHELOGGINGLOG4J-2314720] in org.apache.logging.log4j:log4j-core@2.14.1
    introduced by org.apache.logging.log4j:log4j-core@2.14.1
```

Can you upgrade the fuseki version to 4.3.1. This version fix the issue ([upgrade log4j to 2.15](https://github.com/apache/jena/commits/7f47eaaf7cc0029291ce64790da987ec2d29fdf5))

**Comment by xgaia** [comment]
Thanks for the update !

Could you also re-build the dockerhub image ? https://hub.docker.com/r/secoresearch/fuseki/tags

thanks !

**Comment by yoge1** [comment]
Docker Hub images have now been rebuilt!

https://hub.docker.com/r/secoresearch/fuseki/tags
